# Generated by Django 4.2.2 on 2023-06-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
