# Generated by Django 4.2.2 on 2023-06-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_post_num_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
