# Generated by Django 4.2.2 on 2023-06-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_tablaprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablaprofile',
            name='amigos',
            field=models.ManyToManyField(blank=True, to='UserProfile.tablaprofile'),
        ),
    ]
