# Generated by Django 4.2.2 on 2023-06-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_tablaprofile_amigos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaprofile',
            name='amigos',
        ),
    ]
