# Generated by Django 4.2.2 on 2023-06-22 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProfile', '0004_remove_tablaprofile_amigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablaprofile',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
